name: Monitor Ticketmaster

on:
  schedule:
    # Tenta rodar a cada 3 minutos (*/3)
    - cron: '*/3 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # Impede que duas checagens rodem ao mesmo tempo se uma atrasar
    concurrency: 
      group: monitor-group
      cancel-in-progress: true

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4

      - name: Executar Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: Atualizar Site (GitHub Pages)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update status"
          git push
